version: "3.8"

services:

  wallet-postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - integration

  app:
    container_name: wallet_service
    build: .
    depends_on:
      - wallet-postgresql
    ports:
      - "8081:8081"
    networks:
      - integration
    volumes:
      - ./:/app
      - build:/buildDir
      - gradle-cache:/root/.gradle
      - ~/.gradle/gradle.properties:/root/.gradle/gradle.properties
    environment:
      - GRADLE_OPTS=-Dorg.gradle.project.buildDir=/buildDir/build
      - SPRING_PROFILES_ACTIVE=local
      - DB_HOST=wallet-postgresql
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    command: >
      sh -c "./gradlew --no-daemon flywayMigrate && ./gradlew --no-daemon bootRun"

networks:
  integration:
    external: true

volumes:
  build:
  gradle-cache: